#!/bin/sh
echo starting sever...
python /home/pi/pi_cam_hangout/serverjq/PiBot_remote_control.py >> /var/log/pi_cam.log 2>&1 &
echo starting ssh connection...
ssh -i /home/pi/.ssh/amazon_key.pem -N -g -R :7070:localhost:7070 ec2-user@tesseract-aws.ddns.net
